version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - gosec
    - misspell
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - ^tailscale/
      - ^analyst/src/cli/
      - ^analyst/src/wgcfg/
      - ^android-client/libtailscale/
