services:
  provisioner:
    build:
      context: ../
      dockerfile: provisioning/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
    env_file:
      - provisioner.env
    volumes:
      - provisioner-state:/var/lib/mesh-provisioner

volumes:
  provisioner-state:
