name: Deploy documentation

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-material[imaging]

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@main
        with:
          globs: "docs/**/*.{md,markdown}"

      - name: Build and deploy documentation
        run: mkdocs gh-deploy --force --clean
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
